app_name: jobs

server:
  port: 50303

jobs:
  planned_enabled: false
  injections_path: /var/www/xmp.linkit360.ru/web/injections
  check_prefix: 92

inmem_client:
  timeout: 10

publisher:
  pending_buffer_path: /home/centos/linkit/jobs_pending.json
  chan_capacity: 100
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672

db:
  conn_ttl: -1
  max_open_conns: 15
  max_idle_conns: 10
  timeout: 30
  name: linkit_dev
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit.cz3twmoynbq5.eu-central-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_
