app_name: jobs

server:
  port: 50303

metrics:
  period: 600
  allowed_db_size: 141183828140
  db:
  - linkit_dev

mid_client:
  dsn: :50307
  timeout: 10

jobs:
  planned_enabled: false
  planned_period_minutes: 1
  injections_path: /var/www/xmp.linkit360.ru/web/injections
  log_path: /var/log/linkit/
  check_prefix: 92
  callback_url: http://dev.pk.linkit360.ru/test

publisher:
  chan_capacity: 100
  conn:
    user: linkit
    pass: dg-U_oHhy7-
    host: localhost
    port: 5672

db:
  conn_ttl: -1
  max_open_conns: 3
  max_idle_conns: 1
  timeout: 30
  name: linkit_dev
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit.cz3twmoynbq5.eu-central-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_

db_slave:
  conn_ttl: -1
  max_open_conns: 3
  max_idle_conns: 1
  timeout: 30
  name: linkit_dev
  user: linkit
  pass: E0kZN8pUAs63wePepf
  port: 5432
  host: linkit.cz3twmoynbq5.eu-central-1.rds.amazonaws.com
  ssl_mode: disable
  table_prefix: xmp_
